# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shixuan_sun/project/MOOCDataTransformation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shixuan_sun/project/MOOCDataTransformation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shixuan_sun/project/MOOCDataTransformation/CMakeFiles /home/shixuan_sun/project/MOOCDataTransformation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shixuan_sun/project/MOOCDataTransformation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MOOCDataTransformation

# Build rule for target.
MOOCDataTransformation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MOOCDataTransformation
.PHONY : MOOCDataTransformation

# fast build rule for target.
MOOCDataTransformation/fast:
	$(MAKE) -f CMakeFiles/MOOCDataTransformation.dir/build.make CMakeFiles/MOOCDataTransformation.dir/build
.PHONY : MOOCDataTransformation/fast

lib/jsoncpp/jsoncpp.o: lib/jsoncpp/jsoncpp.cpp.o
.PHONY : lib/jsoncpp/jsoncpp.o

# target to build an object file
lib/jsoncpp/jsoncpp.cpp.o:
	$(MAKE) -f CMakeFiles/MOOCDataTransformation.dir/build.make CMakeFiles/MOOCDataTransformation.dir/lib/jsoncpp/jsoncpp.cpp.o
.PHONY : lib/jsoncpp/jsoncpp.cpp.o

lib/jsoncpp/jsoncpp.i: lib/jsoncpp/jsoncpp.cpp.i
.PHONY : lib/jsoncpp/jsoncpp.i

# target to preprocess a source file
lib/jsoncpp/jsoncpp.cpp.i:
	$(MAKE) -f CMakeFiles/MOOCDataTransformation.dir/build.make CMakeFiles/MOOCDataTransformation.dir/lib/jsoncpp/jsoncpp.cpp.i
.PHONY : lib/jsoncpp/jsoncpp.cpp.i

lib/jsoncpp/jsoncpp.s: lib/jsoncpp/jsoncpp.cpp.s
.PHONY : lib/jsoncpp/jsoncpp.s

# target to generate assembly for a file
lib/jsoncpp/jsoncpp.cpp.s:
	$(MAKE) -f CMakeFiles/MOOCDataTransformation.dir/build.make CMakeFiles/MOOCDataTransformation.dir/lib/jsoncpp/jsoncpp.cpp.s
.PHONY : lib/jsoncpp/jsoncpp.cpp.s

src/TabularData.o: src/TabularData.cpp.o
.PHONY : src/TabularData.o

# target to build an object file
src/TabularData.cpp.o:
	$(MAKE) -f CMakeFiles/MOOCDataTransformation.dir/build.make CMakeFiles/MOOCDataTransformation.dir/src/TabularData.cpp.o
.PHONY : src/TabularData.cpp.o

src/TabularData.i: src/TabularData.cpp.i
.PHONY : src/TabularData.i

# target to preprocess a source file
src/TabularData.cpp.i:
	$(MAKE) -f CMakeFiles/MOOCDataTransformation.dir/build.make CMakeFiles/MOOCDataTransformation.dir/src/TabularData.cpp.i
.PHONY : src/TabularData.cpp.i

src/TabularData.s: src/TabularData.cpp.s
.PHONY : src/TabularData.s

# target to generate assembly for a file
src/TabularData.cpp.s:
	$(MAKE) -f CMakeFiles/MOOCDataTransformation.dir/build.make CMakeFiles/MOOCDataTransformation.dir/src/TabularData.cpp.s
.PHONY : src/TabularData.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/MOOCDataTransformation.dir/build.make CMakeFiles/MOOCDataTransformation.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/MOOCDataTransformation.dir/build.make CMakeFiles/MOOCDataTransformation.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/MOOCDataTransformation.dir/build.make CMakeFiles/MOOCDataTransformation.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/source/JsonSource.o: src/source/JsonSource.cpp.o
.PHONY : src/source/JsonSource.o

# target to build an object file
src/source/JsonSource.cpp.o:
	$(MAKE) -f CMakeFiles/MOOCDataTransformation.dir/build.make CMakeFiles/MOOCDataTransformation.dir/src/source/JsonSource.cpp.o
.PHONY : src/source/JsonSource.cpp.o

src/source/JsonSource.i: src/source/JsonSource.cpp.i
.PHONY : src/source/JsonSource.i

# target to preprocess a source file
src/source/JsonSource.cpp.i:
	$(MAKE) -f CMakeFiles/MOOCDataTransformation.dir/build.make CMakeFiles/MOOCDataTransformation.dir/src/source/JsonSource.cpp.i
.PHONY : src/source/JsonSource.cpp.i

src/source/JsonSource.s: src/source/JsonSource.cpp.s
.PHONY : src/source/JsonSource.s

# target to generate assembly for a file
src/source/JsonSource.cpp.s:
	$(MAKE) -f CMakeFiles/MOOCDataTransformation.dir/build.make CMakeFiles/MOOCDataTransformation.dir/src/source/JsonSource.cpp.s
.PHONY : src/source/JsonSource.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... MOOCDataTransformation"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lib/jsoncpp/jsoncpp.o"
	@echo "... lib/jsoncpp/jsoncpp.i"
	@echo "... lib/jsoncpp/jsoncpp.s"
	@echo "... src/TabularData.o"
	@echo "... src/TabularData.i"
	@echo "... src/TabularData.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/source/JsonSource.o"
	@echo "... src/source/JsonSource.i"
	@echo "... src/source/JsonSource.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

